name: Deploy Web via SSM
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: { AWS_REGION: eu-central-1 }
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Push simple page to all web instances
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=cs1nca-dev-web" \
            --parameters commands="sudo bash -lc 'echo \"<h1>Deployed $GITHUB_SHA on $(date -u)</h1>\" > /usr/share/nginx/html/index.html'"
